### ISSUE TITLE
Create Solidity/Hardhat branch

### ISSUE THREAD

**Issue by DeFiFoFum** [DeFiFoFum/defifofum-monorepo-template#1]
Balancer has created a really nice Solidity development monorepo to support their `BalancerV2` codebase: [balancer-v2-monorepo](https://github.com/balancer-labs/balancer-v2-monorepo ). I would like to pull hardhat development features and monorepo ideas and port them over into this [turborepo](https://turborepo.org/) monorepo. 

## Tasks
- [ ] Create a `hardhat` branch
Provide Typescript tooling to support smart contract:
- [ ] Smart contract types with `typechain`
- [ ] Development
- [ ] Testing
- [ ] Deployment
- [ ] Creating/Publishing any support packages/scripts
